// Generated by GitHub Copilot

/**
 * Player Service Test Suite
 *
 * This test suite validates the dual audio element player system with preloading capabilities.
 * It uses a custom MockHTMLAudioElement to simulate browser audio functionality in Jest.
 *
 * Test coverage includes:
 * - Initialization and setup
 * - Track loading with and without preloading
 * - Preloading system (timing, switching, edge cases)
 * - Playback controls (play, pause, restart, progress)
 * - Volume controls and boundary handling
 * - Progress tracking and auto-preloading triggers
 * - Advanced preloading logic and fallback scenarios
 * - Error handling and edge cases
 * - State management across operations
 */

import { MockHTMLAudioElement } from '../../../__mocks__/HTMLAudioElement';
import * as player from './player';

// Mock document.createElement for audio elements directly in test file
const originalCreateElement = document.createElement.bind(document);

// Simple direct replacement approach
global.document.createElement = (tagName: string) => {
  if (tagName.toLowerCase() === 'audio') {
    return new MockHTMLAudioElement() as any;
  }
  return originalCreateElement(tagName);
};

// Mock requestAnimationFrame
global.requestAnimationFrame = jest.fn((cb) => setTimeout(cb, 0));

describe('Player Service', () => {
  const mockCallbacks = {
    onLoadStart: jest.fn(),
    onCanPlay: jest.fn(),
    onEnded: jest.fn(),
    onError: jest.fn(),
  };

  beforeEach(() => {
    jest.clearAllMocks();
    // Reset player state between tests
    player.unload();
  });

  describe('Initialization', () => {
    test('should initialize dual audio elements', () => {
      expect(() =>
        player.init({
          volumeLevel: 75,
          volumeMuted: false,
          ...mockCallbacks,
        })
      ).not.toThrow();

      // Test that we can call player functions without errors after init
      expect(() => player.getCurrentProgress()).not.toThrow();
      expect(() => player.getCurrentDuration()).not.toThrow();
    });

    test('should set initial volume correctly', () => {
      player.init({
        volumeLevel: 50,
        volumeMuted: false,
        ...mockCallbacks,
      });

      // Volume operations should not throw errors
      expect(() => player.setVolume(75)).not.toThrow();
    });

    test('should handle muted initialization', () => {
      expect(() =>
        player.init({
          volumeLevel: 75,
          volumeMuted: true,
          ...mockCallbacks,
        })
      ).not.toThrow();
    });

    test('should not reinitialize if already initialized', () => {
      const createElementSpy = jest.spyOn(document, 'createElement');

      // First init
      player.init({
        volumeLevel: 75,
        volumeMuted: false,
        ...mockCallbacks,
      });

      const initialCallCount = createElementSpy.mock.calls.length;

      // Second init should not create new elements
      player.init({
        volumeLevel: 75,
        volumeMuted: false,
        ...mockCallbacks,
      });

      expect(createElementSpy.mock.calls.length).toBe(initialCallCount);
    });
  });

  describe('Track Loading', () => {
    beforeEach(() => {
      player.init({
        volumeLevel: 75,
        volumeMuted: false,
        ...mockCallbacks,
      });
    });

    test('should load track normally when no preload available', () => {
      const trackSrc = 'http://example.com/track1.mp3';

      expect(() => player.loadTrack(trackSrc)).not.toThrow();
    });

    test('should load track with custom progress', () => {
      const trackSrc = 'http://example.com/track1.mp3';
      const progress = 30000; // 30 seconds

      expect(() => player.loadTrack(trackSrc, progress)).not.toThrow();
    });

    test('should load track without auto-playing', () => {
      const trackSrc = 'http://example.com/track1.mp3';

      expect(() => player.loadTrack(trackSrc, 0, false)).not.toThrow();
    });

    test('should attempt to use preloaded track when available', async () => {
      const track1 = 'http://example.com/track1.mp3';
      const track2 = 'http://example.com/track2.mp3';

      // Load first track and set next for preloading
      player.loadTrack(track1);
      player.setNextTrack(track2);
      player.preloadNextTrack(track2);

      // Wait for preloading to potentially complete
      await new Promise((resolve) => setTimeout(resolve, 300));

      // Now load the preloaded track - should not throw
      expect(() => player.loadTrack(track2)).not.toThrow();
    });
  });

  describe('Preloading System', () => {
    beforeEach(() => {
      player.init({
        volumeLevel: 75,
        volumeMuted: false,
        ...mockCallbacks,
      });
    });

    test('should set next track for preloading', () => {
      const nextTrackSrc = 'http://example.com/track2.mp3';

      expect(() => player.setNextTrack(nextTrackSrc)).not.toThrow();
    });

    test('should clear next track', () => {
      player.setNextTrack('http://example.com/track2.mp3');
      expect(() => player.clearNextTrack()).not.toThrow();
    });

    test('should start preloading next track', () => {
      const nextTrackSrc = 'http://example.com/track2.mp3';
      player.setNextTrack(nextTrackSrc);

      expect(() => player.preloadNextTrack(nextTrackSrc)).not.toThrow();
    });

    test('should not preload if already preloading', () => {
      const nextTrackSrc = 'http://example.com/track2.mp3';
      player.setNextTrack(nextTrackSrc);

      // Start first preload
      player.preloadNextTrack(nextTrackSrc);

      // Second preload should be ignored (not throw)
      expect(() => player.preloadNextTrack(nextTrackSrc)).not.toThrow();
    });

    test('should handle preloading completion events', async () => {
      const nextTrackSrc = 'http://example.com/track2.mp3';
      player.setNextTrack(nextTrackSrc);
      player.preloadNextTrack(nextTrackSrc);

      // Wait for mock events to fire
      await new Promise((resolve) => setTimeout(resolve, 300));

      // Preloading should have completed without errors
      expect(mockCallbacks.onError).not.toHaveBeenCalled();
    });
  });

  describe('Playback Controls', () => {
    beforeEach(() => {
      player.init({
        volumeLevel: 75,
        volumeMuted: false,
        ...mockCallbacks,
      });
      player.loadTrack('http://example.com/track1.mp3');
    });

    test('should pause playback', () => {
      expect(() => player.pause()).not.toThrow();
    });

    test('should resume playback', () => {
      expect(() => player.resume()).not.toThrow();
    });

    test('should restart track', () => {
      expect(() => player.restart()).not.toThrow();
    });

    test('should set progress', () => {
      expect(() => player.setProgress(30000)).not.toThrow(); // 30 seconds
    });

    test('should handle progress at track boundaries', () => {
      expect(() => player.setProgress(0)).not.toThrow(); // Start
      expect(() => player.setProgress(100000)).not.toThrow(); // End
    });
  });

  describe('Volume Controls', () => {
    beforeEach(() => {
      player.init({
        volumeLevel: 75,
        volumeMuted: false,
        ...mockCallbacks,
      });
    });

    test('should set volume level', () => {
      expect(() => player.setVolume(50)).not.toThrow();
    });

    test('should handle volume boundaries', () => {
      expect(() => player.setVolume(0)).not.toThrow(); // Minimum
      expect(() => player.setVolume(100)).not.toThrow(); // Maximum
    });

    test('should handle extreme volume values gracefully', () => {
      expect(() => player.setVolume(-10)).not.toThrow(); // Negative
      expect(() => player.setVolume(150)).not.toThrow(); // Over 100
    });
  });

  describe('Progress Tracking', () => {
    beforeEach(() => {
      player.init({
        volumeLevel: 75,
        volumeMuted: false,
        ...mockCallbacks,
      });
      player.loadTrack('http://example.com/track1.mp3');
    });

    test('should return current progress', () => {
      const progress = player.getCurrentProgress();
      expect(typeof progress).toBe('number');
      expect(progress).toBeGreaterThanOrEqual(0);
    });

    test('should return current duration', () => {
      const duration = player.getCurrentDuration();
      expect(typeof duration).toBe('number');
      expect(duration).toBeGreaterThanOrEqual(0);
    });

    test('should handle progress updates without next track', () => {
      // No next track set - should not trigger preloading
      expect(() => player.updateProgress(60000)).not.toThrow();
    });

    test('should trigger preloading at 60% progress', () => {
      const nextTrackSrc = 'http://example.com/track2.mp3';
      player.setNextTrack(nextTrackSrc);

      // Mock a 100-second track, trigger at 60% (60 seconds)
      expect(() => player.updateProgress(60000)).not.toThrow();
    });

    test('should trigger preloading at 45 seconds remaining', () => {
      const nextTrackSrc = 'http://example.com/track2.mp3';
      player.setNextTrack(nextTrackSrc);

      // Mock a 100-second track, 44 seconds remaining (56 seconds in)
      expect(() => player.updateProgress(56000)).not.toThrow();
    });

    test('should not retrigger preloading if already preloaded', () => {
      const nextTrackSrc = 'http://example.com/track2.mp3';
      player.setNextTrack(nextTrackSrc);

      // First trigger should start preloading
      player.updateProgress(60000);

      // Second trigger should not cause issues
      expect(() => player.updateProgress(70000)).not.toThrow();
    });

    test('should not preload if duration is zero or invalid', () => {
      const nextTrackSrc = 'http://example.com/track2.mp3';
      player.setNextTrack(nextTrackSrc);

      // Mock zero duration by not having loaded track properly
      // This tests the getCurrentDuration() <= 0 check
      expect(() => player.updateProgress(60000)).not.toThrow();
    });
  });

  describe('Advanced Preloading Logic', () => {
    beforeEach(() => {
      player.init({
        volumeLevel: 75,
        volumeMuted: false,
        ...mockCallbacks,
      });
    });

    test('should handle preloading timing thresholds correctly', () => {
      const currentTrack = 'http://example.com/track1.mp3';
      const nextTrack = 'http://example.com/track2.mp3';

      player.loadTrack(currentTrack);
      player.setNextTrack(nextTrack);

      // Test various progress points
      expect(() => player.updateProgress(30000)).not.toThrow(); // 30% - too early
      expect(() => player.updateProgress(59000)).not.toThrow(); // 59% - just before threshold
      expect(() => player.updateProgress(60000)).not.toThrow(); // 60% - should trigger
      expect(() => player.updateProgress(55000)).not.toThrow(); // 45s remaining - should trigger
    });

    test('should switch to preloaded track successfully', async () => {
      const track1 = 'http://example.com/track1.mp3';
      const track2 = 'http://example.com/track2.mp3';

      // Setup preloading scenario
      player.loadTrack(track1);
      player.setNextTrack(track2);
      player.preloadNextTrack(track2);

      // Wait for preloading events
      await new Promise((resolve) => setTimeout(resolve, 300));

      // Attempt to use preloaded track
      expect(() => player.loadTrack(track2)).not.toThrow();
    });

    test('should fallback gracefully when preloaded track not ready', () => {
      const track1 = 'http://example.com/track1.mp3';
      const track2 = 'http://example.com/track2.mp3';

      // Setup but don't wait for preloading to complete
      player.loadTrack(track1);
      player.setNextTrack(track2);
      player.preloadNextTrack(track2);

      // Immediately try to use - should fallback to regular loading
      expect(() => player.loadTrack(track2)).not.toThrow();
    });
  });

  describe('Error Handling and Edge Cases', () => {
    test('should handle operations before initialization', () => {
      // These should not throw even if called before init
      expect(() => player.getCurrentProgress()).not.toThrow();
      expect(() => player.getCurrentDuration()).not.toThrow();
      expect(() => player.pause()).not.toThrow();
      expect(() => player.resume()).not.toThrow();
      expect(() => player.restart()).not.toThrow();
      expect(() => player.setVolume(75)).not.toThrow();
      expect(() => player.setProgress(30000)).not.toThrow();
    });

    test('should handle unload gracefully', () => {
      player.init({
        volumeLevel: 75,
        volumeMuted: false,
        ...mockCallbacks,
      });

      player.loadTrack('http://example.com/track1.mp3');

      expect(() => player.unload()).not.toThrow();
    });

    test('should handle unload before initialization', () => {
      expect(() => player.unload()).not.toThrow();
    });

    test('should handle multiple unload calls', () => {
      player.init({
        volumeLevel: 75,
        volumeMuted: false,
        ...mockCallbacks,
      });

      expect(() => player.unload()).not.toThrow();
      expect(() => player.unload()).not.toThrow(); // Second call
    });

    test('should handle preloading operations without next track', () => {
      player.init({
        volumeLevel: 75,
        volumeMuted: false,
        ...mockCallbacks,
      });

      // These should handle gracefully when no next track is set
      expect(() => player.updateProgress(60000)).not.toThrow();
      expect(() => player.clearNextTrack()).not.toThrow();
    });

    test('should handle invalid track sources', () => {
      player.init({
        volumeLevel: 75,
        volumeMuted: false,
        ...mockCallbacks,
      });

      expect(() => player.loadTrack('')).not.toThrow(); // Empty string
      expect(() => player.loadTrack('invalid-url')).not.toThrow(); // Invalid URL
    });

    test('should handle negative progress values', () => {
      player.init({
        volumeLevel: 75,
        volumeMuted: false,
        ...mockCallbacks,
      });

      player.loadTrack('http://example.com/track1.mp3');

      expect(() => player.setProgress(-1000)).not.toThrow(); // Negative progress
      expect(() => player.updateProgress(-1000)).not.toThrow(); // Negative update
    });
  });

  describe('State Management', () => {
    beforeEach(() => {
      player.init({
        volumeLevel: 75,
        volumeMuted: false,
        ...mockCallbacks,
      });
    });

    test('should maintain state across multiple track loads', () => {
      const track1 = 'http://example.com/track1.mp3';
      const track2 = 'http://example.com/track2.mp3';
      const track3 = 'http://example.com/track3.mp3';

      // Load multiple tracks in sequence
      expect(() => player.loadTrack(track1)).not.toThrow();
      expect(() => player.setNextTrack(track2)).not.toThrow();
      expect(() => player.loadTrack(track2)).not.toThrow();
      expect(() => player.setNextTrack(track3)).not.toThrow();
      expect(() => player.loadTrack(track3)).not.toThrow();
    });

    test('should handle rapid next track changes', () => {
      const tracks = [
        'http://example.com/track1.mp3',
        'http://example.com/track2.mp3',
        'http://example.com/track3.mp3',
        'http://example.com/track4.mp3',
      ];

      player.loadTrack(tracks[0]);

      // Rapidly change next track
      tracks.slice(1).forEach((track) => {
        expect(() => player.setNextTrack(track)).not.toThrow();
      });
    });

    test('should clear state properly on unload', () => {
      // Setup some state
      player.loadTrack('http://example.com/track1.mp3');
      player.setNextTrack('http://example.com/track2.mp3');
      player.preloadNextTrack('http://example.com/track2.mp3');

      // Unload should clear everything
      player.unload();

      // Operations after unload should still not throw
      expect(() => player.getCurrentProgress()).not.toThrow();
      expect(() => player.updateProgress(60000)).not.toThrow();
    });
  });
  describe('Configuration', () => {
    test('should respect enablePreloading setting', () => {
      player.init({
        volumeLevel: 75,
        volumeMuted: false,
        ...mockCallbacks,
      });

      // Set next track and try to preload
      player.setNextTrack('http://example.com/track2.mp3');

      // Should be able to call preload function without errors
      expect(() => player.preloadNextTrack('http://example.com/track2.mp3')).not.toThrow();
    });
  });

  describe('Detailed Volume Behavior', () => {
    beforeEach(() => {
      player.init({
        volumeLevel: 75,
        volumeMuted: false,
        ...mockCallbacks,
      });
    });

    test('should apply volume to both audio elements', () => {
      const createElementSpy = jest.spyOn(document, 'createElement');

      player.setVolume(50);

      // Both elements should have been created and volume set
      const audioElements = createElementSpy.mock.results
        .filter((result) => result.value && typeof result.value.volume !== 'undefined')
        .map((result) => result.value);

      audioElements.forEach((element) => {
        expect(element.volume).toBe(0.5); // 50/100
      });
    });

    test('should handle volume correctly during initialization', () => {
      // Unload first to reset
      player.unload();

      const createElementSpy = jest.spyOn(document, 'createElement');

      // Initialize with specific volume
      player.init({
        volumeLevel: 80,
        volumeMuted: false,
        ...mockCallbacks,
      });

      const audioElements = createElementSpy.mock.results
        .filter((result) => result.value && typeof result.value.volume !== 'undefined')
        .map((result) => result.value);

      audioElements.forEach((element) => {
        expect(element.volume).toBe(0.8); // 80/100
      });
    });

    test('should mute correctly during initialization', () => {
      // Unload first to reset
      player.unload();

      const createElementSpy = jest.spyOn(document, 'createElement');

      // Initialize muted
      player.init({
        volumeLevel: 80,
        volumeMuted: true,
        ...mockCallbacks,
      });

      const audioElements = createElementSpy.mock.results
        .filter((result) => result.value && typeof result.value.volume !== 'undefined')
        .map((result) => result.value);

      audioElements.forEach((element) => {
        expect(element.volume).toBe(0); // Muted
      });
    });
  });

  describe('Player Element Switching Logic', () => {
    beforeEach(() => {
      player.init({
        volumeLevel: 75,
        volumeMuted: false,
        ...mockCallbacks,
      });
    });

    test('should use different elements for current and preloaded tracks', async () => {
      const track1 = 'http://example.com/track1.mp3';
      const track2 = 'http://example.com/track2.mp3';

      // Load first track
      player.loadTrack(track1);

      // Set up preloading
      player.setNextTrack(track2);
      player.preloadNextTrack(track2);

      // Wait for preloading
      await new Promise((resolve) => setTimeout(resolve, 300));

      // Switch to preloaded track
      player.loadTrack(track2);

      // Should not throw and should have switched elements
      expect(() => player.getCurrentProgress()).not.toThrow();
      expect(() => player.getCurrentDuration()).not.toThrow();
    });

    test('should pause other player when loading new track', () => {
      const track1 = 'http://example.com/track1.mp3';
      const track2 = 'http://example.com/track2.mp3';

      // Load first track
      player.loadTrack(track1);
      player.resume(); // Start playing

      // Load second track - should pause first
      player.loadTrack(track2);

      // Should not cause conflicts
      expect(() => player.pause()).not.toThrow();
    });
  });

  describe('Progress and Duration Accuracy', () => {
    beforeEach(() => {
      player.init({
        volumeLevel: 75,
        volumeMuted: false,
        ...mockCallbacks,
      });
      player.loadTrack('http://example.com/track1.mp3');
    });

    test('should return accurate progress values', () => {
      // Set specific progress
      player.setProgress(45000); // 45 seconds

      const progress = player.getCurrentProgress();
      expect(progress).toBe(45); // Should be in seconds
    });

    test('should return mock duration', () => {
      const duration = player.getCurrentDuration();
      expect(duration).toBe(100); // Mock duration from HTMLAudioElement
    });
    test('should handle progress updates correctly', () => {
      const nextTrack = 'http://example.com/track2.mp3';
      player.setNextTrack(nextTrack);

      // Test progress that should trigger preloading (60%)
      // The actual preloading behavior is internal, just test it doesn't throw
      expect(() => player.updateProgress(60000)).not.toThrow(); // 60 seconds = 60% of 100s track
    });

    test('should handle progress that triggers 45s remaining threshold', () => {
      const nextTrack = 'http://example.com/track2.mp3';
      player.setNextTrack(nextTrack);

      // Test progress that triggers 45s remaining threshold
      expect(() => player.updateProgress(56000)).not.toThrow(); // 56s = 44s remaining (less than 45s)
    });
  });

  describe('Event Handling and Callbacks', () => {
    test('should call provided callbacks during initialization', () => {
      // Simply test that initialization works with callbacks
      expect(() =>
        player.init({
          volumeLevel: 75,
          volumeMuted: false,
          ...mockCallbacks,
        })
      ).not.toThrow();

      // Verify that the player was initialized correctly
      expect(() => player.getCurrentProgress()).not.toThrow();
      expect(() => player.getCurrentDuration()).not.toThrow();
    });

    test('should handle track loading events', async () => {
      player.init({
        volumeLevel: 75,
        volumeMuted: false,
        ...mockCallbacks,
      });

      player.loadTrack('http://example.com/track1.mp3');

      // Wait for mock events to fire
      await new Promise((resolve) => setTimeout(resolve, 100));

      // Mock should have triggered some events
      expect(mockCallbacks.onLoadStart).toHaveBeenCalled();
    });
  });

  describe('Preloading State Management', () => {
    beforeEach(() => {
      player.init({
        volumeLevel: 75,
        volumeMuted: false,
        ...mockCallbacks,
      });
    });

    test('should track preloading state correctly', () => {
      const track1 = 'http://example.com/track1.mp3';
      const track2 = 'http://example.com/track2.mp3';

      player.loadTrack(track1);
      player.setNextTrack(track2);

      // Start preloading
      player.preloadNextTrack(track2);

      // Try to preload again - should be ignored
      expect(() => player.preloadNextTrack(track2)).not.toThrow();

      // Should be able to handle multiple preload attempts gracefully
    });

    test('should reset preloading state after track switch', async () => {
      const track1 = 'http://example.com/track1.mp3';
      const track2 = 'http://example.com/track2.mp3';
      const track3 = 'http://example.com/track3.mp3';

      // Set up preloading scenario
      player.loadTrack(track1);
      player.setNextTrack(track2);
      player.preloadNextTrack(track2);

      // Wait for preloading to complete
      await new Promise((resolve) => setTimeout(resolve, 300));

      // Switch to preloaded track
      player.loadTrack(track2);

      // Should be able to set new next track
      expect(() => player.setNextTrack(track3)).not.toThrow();
      expect(() => player.preloadNextTrack(track3)).not.toThrow();
    });

    test('should clear preloading state on unload', () => {
      const track2 = 'http://example.com/track2.mp3';

      player.setNextTrack(track2);
      player.preloadNextTrack(track2);

      // Unload should reset everything
      player.unload();

      // Should be able to start fresh
      expect(() => player.setNextTrack(track2)).not.toThrow();
      expect(() => player.preloadNextTrack(track2)).not.toThrow();
    });
  });
});
